name: If Condition Demo
on:
  push:
    branches:
      - main
      - develop
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Running with condition if branch is main
        if: github.ref_name == 'main'
        run: echo "with if conditions"

      - name: Running without conditions
        run: echo "without conditions"
